# 端口
server:
  port: 9999

spring:
  # 数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/product_source?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: pig
      password: pig

  #返回统一格式的时间json字符串
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  configuration:
    # 控制台打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 配置驼峰映射
    map-underscore-to-camel-case: true
  # 配置类型别名所在的包
  type-aliases-package: com.briup.product_source.pojo
  # mapper映射文件所在的位置
  mapper-locations: classpath:mappers/**/*.xml
